### ISSUE TITLE
issue building in Alpine container

### ISSUE THREAD

**Issue by alienatorZ** [airbusgeo/godal#124]
When building an app using godal in alpine I get this error. The app builds fine on my Ubuntu machine. Can anyone point me in the right direction?

4.548 # github.com/airbusgeo/godal
4.548 /go/pkg/mod/github.com/airbusgeo/godal@v0.0.11/errors.go:37:27: undefined: ErrorCategory
4.548 /go/pkg/mod/github.com/airbusgeo/godal@v0.0.11/options.go:138:28: undefined: ResamplingAlg
4.548 /go/pkg/mod/github.com/airbusgeo/godal@v0.0.11/options.go:159:8: undefined: Band
4.548 /go/pkg/mod/github.com/airbusgeo/godal@v0.0.11/options.go:179:17: undefined: Band
4.548 /go/pkg/mod/github.com/airbusgeo/godal@v0.0.11/options.go:180:17: undefined: Band
4.548 /go/pkg/mod/github.com/airbusgeo/godal@v0.0.11/options.go:197:17: undefined: Band
4.548 /go/pkg/mod/github.com/airbusgeo/godal@v0.0.11/options.go:277:15: undefined: ResamplingAlg
4.548 /go/pkg/mod/github.com/airbusgeo/godal@v0.0.11/options.go:310:41: undefined: ResamplingAlg
4.548 /go/pkg/mod/github.com/airbusgeo/godal@v0.0.11/options.go:1013:4: undefined: ResamplingAlg
4.548 /go/pkg/mod/github.com/airbusgeo/godal@v0.0.11/options.go:1062:8: undefined: Band
4.548 /go/pkg/mod/github.com/airbusgeo/godal@v0.0.11/options.go:1062:8: too many errors

**Comment by tbonfort** [comment]
strange... maybe your distro is missing a C/C++ toolchain? (as ErrorCategory is defined in godal.go which requires cgo)

**Comment by tbonfort** [comment]
fixed by installing a c++ compiler, closing. re-open if not
