### ISSUE TITLE
找不到gdal库

### ISSUE THREAD

**Issue by df-bingo** [airbusgeo/godal#130]
![image](https://github.com/user-attachments/assets/ae1e0af8-a760-40c1-866e-d99cde20fb61)

pkg-config可以找到gdal.pc文件
![image](https://github.com/user-attachments/assets/daf2f317-2ec6-4c3a-b745-eb7b5df5ab4d)

gdal.pc文件内容也没问题
![image](https://github.com/user-attachments/assets/82049471-b82a-479d-b0cc-9e6b75b2145c)

请教下还有什么原因导致godal找不到gdal库

运行环境如下：
go version go1.22.5 linux/amd64
22.04.2 LTS (Jammy Jellyfish)
gdal 3.6.3
godal v0.0.11

**Comment by tbonfort** [comment]
I suspect that you don't have a `gcc` compiler installed. If that is not the case I will need more error messages because what you provided is not enough

**Comment by df-bingo** [comment]
Absolutely, I am extremely grateful for your invaluable guidance.
