### ISSUE TITLE
Vector layer creation support

### ISSUE THREAD

**Issue by apjoseph** [airbusgeo/godal#131]
On the vector side of the API, support for transferring layers between datasources and creating new layers is fairly limited due to missing support for setting fields on new features and no ExecuteSQL / transaction support.

These methods are particularly necessary for /vsimem datasets which are only accessible through GDAL's API.

**Comment by tbonfort** [comment]
Acknowledged... if you want to work on a PR adding a clean/stable vector API please do so, I'll be happy to help review it.

In the mean time, here's an admittedly clunky but working solution for setting fields on memory datasets:

```go
memds, _ := godal.CreateVector(godal.Memory, "")
lyr, _ := memds.CreateLayer("tileindex", srs, godal.GTPolygon,
					godal.NewFieldDefinition("location", godal.FTString))
geom, _ := godal.NewGeometryFromWKT("whatever wkt")
defer geom.Close()
feat, _ := lyr.NewFeature(geom)
defer feat.Close()
attrs := feat.Fields()
field := attrs["location"]
feat.SetFieldValue(field, tileName)
lyr.UpdateFeature(feat)
```
