### ISSUE TITLE
[question] Cannot convert GML to other formats

### ISSUE THREAD

**Issue by IceflowRE** [airbusgeo/godal#138]
Iam trying to convert a GML into a dxf and a geojson with the following code. Used GDAL 3.4.1 and 3.6.4.
And encountering multiple problems:
1. The dxf file is empty and just the dxf.tmp file has content
2. The geojson is truncated and ends unexpectedly.

```go
package main

import (
	"fmt"

	"github.com/airbusgeo/godal"
)

func main() {
	godal.RegisterAll()
	gmlDs, err := godal.Open("example.gml", godal.VectorOnly())
	if err != nil {
		panic(err)
	}
	_, err = gmlDs.VectorTranslate("converted.dxf", []string{"-f", "DXF", "-skipfailures"})
	if err != nil {
		fmt.Println("================")
		fmt.Println(err)
		fmt.Println("================")

	}
	fmt.Println(":::::::::::::::")

	_, err = gmlDs.VectorTranslate("converted.geojson", []string{"-t_srs", "epsg:4326", "-f", "GeoJSON", "-skipfailures"})
	if err != nil {
		fmt.Println("================")
		fmt.Println(err)
		fmt.Println("================")

	}
	gmlDs.Close()
}
```

My example gml is from here (22kb and free to use) https://www.wfs.nrw.de/geobasis/wfs_nw_alkis_vereinfacht?REQUEST=GetFeature&RESULTTYPE=RESULTS&OUTPUTFORMAT=application%2Fgml%2Bxml%3B+version%3D3.2&SRSNAME=urn%3Aogc%3Adef%3Acrs%3AEPSG%3A%3A25832&VERSION=2.0.0&TYPENAMES=ave%3ANutzung&SERVICE=WFS&COUNT=50

**Comment by tbonfort** [comment]
You must capture the first result from glmds.VectorTranslate() (i.e. not only `err`) and call Close() on it.

**Comment by IceflowRE** [comment]
> You must capture the first result from glmds.VectorTranslate() (i.e. not only `err`) and call Close() on it.

https://github.com/airbusgeo/godal/blob/fbf96e7a81be6dd88708912977e8f9960df050df/godal.go#L2515
If an error is returned the result is always `nil`, i cannot capture the result.

changing it to 
```go
return &Dataset{majorObject{C.GDALMajorObjectH(hndl)}}, err
```
fixed it.

**Comment by tbonfort** [comment]
Do I understand this correctly: you ran the conversion with -skipfailures, and godal's behavior of treating warnings as errors meant that the conversion returned (nil,error), whereas in fact you had expected the result to be (dataset*,nil)?
If so:
- it is expected behavior that any godal function will only return exactly one of returnValue|error (i.e. never both)
- the correct workaround (that I understand you used) is to pass a custom ErrorLogger which will not fail on gdal warnings
- there is effectively a possible memory leak when not passing a custom error logger, as the gdal library will in that case return a dataset that is never closed. the godal c++ wrapper should be fixed to call GDALClose on the returned dataset in that case.

**Comment by IceflowRE** [comment]
> Do I understand this correctly: you ran the conversion with -skipfailures, and godal's behavior of treating warnings as errors meant that the conversion returned (nil,error), whereas in fact you had expected the result to be (dataset*,nil)?

Yes, i initially expected that a dataset will be returned regardless.

> If so:
> 
>     * it is expected behavior that any godal function will only return exactly one of returnValue|error (i.e. never both)
Yes.
>     * the correct workaround (that I understand you used) is to pass a custom ErrorLogger which will not fail on gdal warnings

Yes, i just skip away all errors.
```go
ignoreErrs := func(ec godal.ErrorCategory, code int, msg string) error {
	return nil
}
``` 
>     * there is effectively a possible memory leak when not passing a custom error logger, as the gdal library will in that case return a dataset that is never closed. the godal c++ wrapper should be fixed to call GDALClose on the returned dataset in that case.

Yes, i do that. Basically resulting in
```go
// ignoring returned error as all are ignored
ds, _ := srcDs.VectorTranslate(convertedName, switches, godal.ErrLogger(ignoreErrs))
// nil check, as i might have thrown away an error which results not in a valid dataset
if ds == nil {
	return fmt.Errorf("failed to convert")
}
err = ds.Close()
if err != nil {
	return err
}
```
