### ISSUE TITLE
How do I read the window and resampling?

### ISSUE THREAD

**Issue by sshuair** [airbusgeo/godal#31]
This is not an issue, but want some help.
**I want to read part of the image from the large geotiff with resampling to some scaling.**
- upsampling: The read window is (0, 0, 1024, 1024) and the out image shape is 2048x2048. 
- downsampling: The read window is (0, 0, 2048, 2048) and the out image shape is 1024x1024. 

And both the output image's bbox is same. How can I get this?

Could you do me a favor?

**Comment by sshuair** [comment]
I think I known how to do that, the follow code can do this. It's ugly😂,   I an new to golang


```golang

func Spliter(imagePath string, splitSize int) {
	// reference: https://github.com/airbusgeo/geocube/blob/main/internal/geocube/image.go
	// input params
	// var readBands = []int{}

	godal.RegisterAll()
	srcRasDs, err := godal.Open(imagePath)
	if err != nil {
		panic(err)
	}
	// srcVecDs, err := godal.Open(vectorPath)
	// if err != nil {
	// 	panic(err)
	// }

	// print the basic info
	structure := srcRasDs.Structure()
	fmt.Printf("Size is %dx%dx%d\n", structure.SizeX, structure.SizeY, structure.NBands)
	if pj := srcRasDs.Projection(); pj != "" {
		fmt.Printf("Projection is '%s'\n", pj)
	}

	// read window data
	dtype := structure.DataType
	outSize := splitSize * 2
	img := make([]byte, dtype.Size()*3*outSize*outSize)
	// opt := godal.DatasetIOOption({"resampling":godal.})

	// optRead := godal.ConfigOption("dsWidth: 1024", "dsHeight: 1024")
	// optRead := godal.DatasetIOOption
	// a := map[string]int{"dsWidth": 1024, "dsHeight": 1024}
	resampling := godal.Resampling(1)
	windowRead := godal.Window(splitSize, splitSize)
	srcRasDs.Read(0, 0, img, outSize, outSize, resampling, windowRead)

	dstDS, _ := godal.Create(godal.GTiff, "split-upsample-2.tif", 3, dtype, outSize, outSize)
	defer dstDS.Close()

	// set geotranform
	gt, err := srcRasDs.GeoTransform()
	gt[1] = gt[1] / 2
	gt[5] = gt[5] / 2
	dstDS.SetGeoTransform(gt)

	// set crs
	sr := srcRasDs.SpatialRef()
	dstDS.SetSpatialRef(sr)
	// optWrite := godal.ConfigOption("dsWidth: 2048", "dsHeight: 2048")
	windowWrite := godal.Window(outSize, outSize)
	dstDS.Write(0, 0, img, outSize, outSize, resampling, windowWrite)

}

```

**Comment by tbonfort** [comment]
At first glance, this is nearly the correct code for the upsampling case:
```
img := make([]byte, dtype.Size()*3*outSize*outSize)
```
should be
```
img := make([]float64,structure.NBands*outSize*outSize)
```
(replace float64 with uint16, uint32, etc... depending on your use case)

For the resampling, you could/should directly use
```
srcRasDs.Read(0, 0, img, outSize, outSize, godal.Bilinear, windowRead)
```

**Comment by sshuair** [comment]
Thanks for your advice. I am going to use the package for a while. I will keep reporting bugs usage scenario.
 BTW, Great Job!

**Comment by sshuair** [comment]
@tbonfort this seems not work for me `srcRasDs.Read(0, 0, img, outSize, outSize, godal.Bilinear, windowRead)`

![image](https://user-images.githubusercontent.com/5787131/125384000-dfa58e00-e3ca-11eb-8235-d73091931edf.png)

**Comment by tbonfort** [comment]
> @tbonfort this seems not work for me `srcRasDs.Read(0, 0, img, outSize, outSize, godal.Bilinear, windowRead)`

Sorry for the confusion, the *correct* usage is `godal.Resampling(godal.Bilinear)`, which is equivalent but more readable than `godal.Resampling(1)`
