### ISSUE TITLE
can not create the OpenJPEG format data

### ISSUE THREAD

**Issue by sshuair** [airbusgeo/godal#34]
this is the code :

```go
package main

import (
	"github.com/airbusgeo/godal"
)

func main() {
	godal.RegisterAll()
	tifname := "aa.tif"
	dsTif, _ := godal.Create(godal.GTiff, tifname, 1, godal.Byte, 20, 20)  // work
	dsTif.Close()

	jpegname := "bb.jpg"
	dsJpg, _ := godal.Create(godal.OpenJPEG, jpegname, 1, godal.Byte, 20, 20) // not work
	dsJpg.Close()
}

```

the error is 
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4430e42]

goroutine 1 [running]:
github.com/airbusgeo/godal.(*Dataset).Close(0x0, 0x0, 0x0, 0x0, 0x1, 0x1)
        /Users/sshuair/go/pkg/mod/github.com/airbusgeo/godal@v0.0.3/godal.go:1283 +0xa2
main.main()
        /Users/sshuair/test/test.go:15 +0x12b
exit status 2
```

**Comment by tbonfort** [comment]
You should catch and inspect the error returned by Create()

**Comment by sshuair** [comment]
I got the the error message.`GDALDriver::Create() ... no create method implemented for this format.`

 I want to create `JPEG` not `JEPG2000`(I add the JPEG driver in the `driver.go`).  But the GDAL only support `CreateCopy` the `JPEG` format. But I am not finding the `CreateCopy` method in `godal.go`. Any plan to support that? and the

**Comment by tbonfort** [comment]
There are no current plans to add CreateCopy. We do implement dataset.Translate which I think supports 100% of the functionality of CreateCopy. If there is something missing with Translate, feel free to open a PR for CreateCopy
