### ISSUE TITLE
Trouble opening NETCDF dataset

### ISSUE THREAD

**Issue by thomascoquet** [airbusgeo/godal#42]
Hello Thomas,
I am trying to open a netcdf dataset (Sentinel 5P).

`gdalinfo NETCDF:"/home/thomascoquet/product.nc":/PRODUCT/methane_mixing_ratio_bias_corrected` -> works perfectly.

Using godal:
```golang
func TestOpen(t *testing.T) {
	godal.RegisterRaster(godal.GTiff)
	ds, err := godal.Open("/home/thomascoquet/test.tif")
	assert.Nil(t, err)
	ds.Close()
} 
// OK, not a problem of file access

func TestGeoloc(t *testing.T) {
	godal.RegisterRaster(
		//godal.DriverName("KEA"),
		//godal.DriverName("BAG"),
		//godal.DriverName("HDF5"),
		//godal.DriverName("HDF5Image"),
		//godal.DriverName("HDF4"),
		//godal.DriverName("HDF4Image"),
		godal.DriverName("GMT"),
		godal.DriverName("netCDF"),
	)
	ds, err := godal.Open(`NETCDF:"/home/thomascoquet/product.nc":/PRODUCT/methane_mixing_ratio_bias_corrected`)
	assert.Nil(t, err)
}
```

```
--- FAIL: TestGeoloc (0.00s)
    .../read_test.go:23: 
        	Error Trace:	read_test.go:23
        	Error:      	Expected nil, but got: &errors.errorString{s:"NETCDF:\"/home/thomascoquet/product.nc\":/PRODUCT/methane_mixing_ratio_bias_corrected: No such file or directory"}
        	Test:       	TestGeoloc
```

What is the right syntax to open a subdataset? Reading the doc:
> name may be a filename or any supported string supported by gdal (e.g. a /vsixxx path,
> the xml string representing a vrt dataset, etc...)

I was expecting it to work.

An example file:
`wget --content-disposition --continue --user=s5pguest --password=s5pguest "https://s5phub.copernicus.eu/dhus/odata/v1/Products('3fcea3d2-daab-4fa0-a09d-91b52f20ba10')/\$value" -O product.nc`

Thanks!

**Comment by tbonfort** [comment]
What happens if you open:
```
ds, err := godal.Open(`NETCDF:/home/thomascoquet/product.nc:/PRODUCT/methane_mixing_ratio_bias_corrected`)
```
i.e. without the "

**Comment by thomascoquet** [comment]
Ok, found the culprit. I had left in my code all the driver registrations for HDF4 and 5 (I commented it in the issue to make everything clearer).
It appears that I need to follow exactly the order of https://github.com/OSGeo/gdal/blob/master/gdal/frmts/gdalallregister.cpp

```golang
	godal.RegisterRaster(
		godal.DriverName("GMT"),
		godal.DriverName("netCDF"),
		godal.DriverName("HDF4"),
		godal.DriverName("HDF4Image"),
		godal.DriverName("KEA"),
		godal.DriverName("BAG"),
		godal.DriverName("HDF5"),
		godal.DriverName("HDF5Image"),
	)
```

In particular:
```golang
	godal.RegisterRaster(
		godal.DriverName("KEA"),
		godal.DriverName("GMT"),
		godal.DriverName("netCDF"),
	) // -> does not work
	godal.RegisterRaster(
		godal.DriverName("GMT"),
		godal.DriverName("netCDF"),
		godal.DriverName("KEA"),
	) // -> works
```
